name: Mobile CI/CD - Android APK Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual trigger

env:
  NODE_VERSION: "20.x"
  JAVA_VERSION: "17"

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.pnpm-store
            ~/.android/cache
            ~/.gradle/caches
          key: ${{ runner.os }}-deps-${{ hashFiles('pnpm-lock.yaml', 'android/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli @capacitor/cli

      - name: Build Ionic app
        run: ionic build --prod

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Clean Android project
        run: cd android && ./gradlew clean

      - name: Build Android Debug APK
        run: cd android && ./gradlew assembleDebug

      - name: Build Android Release APK (unsigned)
        run: cd android && ./gradlew assembleRelease

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
          retention-days: 30

      - name: Get APK info
        run: |
          echo "Debug APK size: $(du -h android/app/build/outputs/apk/debug/app-debug.apk | cut -f1)"
          echo "Release APK size: $(du -h android/app/build/outputs/apk/release/app-release-unsigned.apk | cut -f1)"
          echo "Debug APK path: android/app/build/outputs/apk/debug/app-debug.apk"
          echo "Release APK path: android/app/build/outputs/apk/release/app-release-unsigned.apk"

  # Optional: Sign release APK (requires secrets)
  sign-release-apk:
    name: Sign Release APK
    runs-on: ubuntu-latest
    needs: build-android
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Download Release APK
        uses: actions/download-artifact@v4
        with:
          name: android-release-apk
          path: ./

      - name: Sign APK
        if: env.ANDROID_KEYSTORE_BASE64 != ''
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > release.keystore
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA256 \
            -keystore release.keystore \
            -storepass "$ANDROID_KEYSTORE_PASSWORD" \
            -keypass "$ANDROID_KEY_PASSWORD" \
            app-release-unsigned.apk \
            "$ANDROID_KEY_ALIAS"
          mv app-release-unsigned.apk app-release-signed.apk

      - name: Upload Signed APK
        if: env.ANDROID_KEYSTORE_BASE64 != ''
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        uses: actions/upload-artifact@v4
        with:
          name: android-release-signed-apk
          path: app-release-signed.apk
          retention-days: 90
